services:
  app:
    container_name: library-app
    image: yiisoftware/yii2-php:8.1-apache
    restart: always
    environment:
      APP_ENV: dev
      FRONTEND_URL: 'http://localhost'
      GH_REPO_URL: 'https://github.com/terratensor/kob-library-app'
      MANTICORE_DB_NAME_COMMON: 'library2025'
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./webui/app:/app:delegated
    ports:
      - '80:80'
    networks:
      - library-net

  manticore:
    container_name: library-manticore
    image: manticoresearch/manticore
    restart: always
    ports:
      - "127.0.0.1:9308:9308" # Локально для отладки (необязательно)
    networks:
      - library-net
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    environment:
      - EXTRA=1
    volumes:
      - ./manticore/data:/var/lib/manticore
      - ./manticore/logs:/var/log/manticore
      # - manticore:/var/lib/manticore
      # - manticore:/var/log/manticore    

  manticore-proxy:
    container_name: library-manticore-proxy
    build: ./proxy
    restart: always
    ports:
      - "1122:9308" # Наружу 1122 → внутри 9308
    networks:
      - library-net
    environment:
      - MANTICORE_API_KEY_FILE=/run/secrets/manticore_api_key
      - MANTICORE_HOST=manticore:9308 # Адрес Manticore в Docker-сети
    secrets:
      - manticore_api_key
    depends_on:
      - manticore

# volumes:
#   manticore:


secrets:
  manticore_api_key:
    file: ./secrets/manticore_api_key

networks:
  library-net:
    name: library-net
