# Маппинг имен папок к отображаемым названиям
mappings:
  flibusta_2023_143865: Флибуста
  flibusta_2025_21388: Флибуста
  geomatrix_geo_library: Географическая библиотека
  militera_2023_11360: Милитера
