env: "local" # Окружение - local, dev или prod
concurrency: 20
volume: "../common/"
manticore:
  engine: "rowwise"
  host: "localhost"
  index: "library2025"
  port: 9308
batch_size: 5000 # размер пакета по умолчанию (default batch size)
min_par_size: 300 #граница минимального размера параграфа в символах, если 0, то без склейки параграфов
opt_par_size: 1800 #граница оптимального размера параграфа в символах, если 0, то без склейки параграфов
max_par_size: 3500 #граница максимального размера параграфа в символах, если 0, то без склейки параграфов
broken_docx_mode: true
pdf_mode: true  # Включить обработку PDF
epub_mode: true # Включить обработку EPUB
filters:
  cut_base64: true
  # Редим cut_base64_recursive имеет смысл включать дополнительно к режиму cut_base64. 
  # В режиме cut_base64_recursive в билдере включается рекурсивная вырезка base64-кодированных данных, 
  # дополнительный фильтр, на этапе когда параграф уже полностью сформирован.  
  # Позволяет доиться дополнительного незначительного уменьшения «мусора» в параграфе.
  cut_base64_recursive: false
